kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-ace
subjects:
  - kind: ServiceAccount
    name: ace-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipelines-scc-rolebinding-ace
subjects:
  - kind: ServiceAccount
    name: ace-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipelines-scc-clusterrole