apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  name: POLICY_NAME
  labels:
    version: 'POLICY_VERSION'
    generated-date: 'GENERATED_DATE'
spec:
  contents: CONTENT_BAR
  type: policyproject