apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: app-configure-task
spec:
  workspaces:
    - name: source
  params:
    - name: project_path
      type: string 
    - name: output_file
      type: string
    - name: image
      type: string
    - name: app_version
      type: string
  steps:
   - name: policy-package
     image: registry.access.redhat.com/ubi8/ubi:latest
     workingDir: $(workspaces.source.path)/$(params.project_path)
     script: |
        #!/bin/sh
        export CURRENT_DATE=$(date | sed 's| |_|g'| sed 's|:|_|g')
        sed -e "s|IMAGE_NAME|$(params.image)|g" templates/ace-instance.yaml > $(params.output_file)
        sed -i -e "s|IS_VERSION|$(params.app_version)|g" $(params.output_file)
        sed -i -e "s|GENERATED_DATE|$CURRENT_DATE|g" $(params.output_file)
        
        cat $(params.output_file)