apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: policy-package-task
spec:
  workspaces:
    - name: source
  params:
    - name: bar_file
      type: string 
    - name: project_name
      type: string
    - name: project_path
      type: string 
  steps:
   - name: policy-package
     image: cp.icr.io/cp/appc/ace-server-prod:12.0.5.0-r3-20220830-142002@sha256:084cbd25b8af37c841f0b8d1ffc401e2805018baeb4ef6997a2ce9c1c97a1441
     workingDir: $(workspaces.source.path)/$(params.project_path)
     script: |
        #!/bin/sh
        
        export LICENSE=accept
        source /opt/ibm/ace-12/server/bin/mqsiprofile

        /opt/ibm/ace-12/server/bin/mqsipackagebar -w $(pwd) -a $(params.bar_file) -k $(params.project_name)

        ls -al 