apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: policy-configure-task
spec:
  workspaces:
    - name: source
  params:
    - name: bar_file
      type: string 
    - name: project_path
      type: string 
    - name: output_file
      type: string
    - name: policy_name
      type: string
    - name: policy_version
  steps:
   - name: policy-package
     image: registry.access.redhat.com/ubi8/ubi:latest
     workingDir: $(workspaces.source.path)/$(params.project_path)
     script: |
        #!/bin/sh
        
        export ENCODED_BAR=$(base64 -i $(params.bar_file) -w 0)

        sed -e "s|CONTENT_BAR|$ENCODED_BAR|g" templates/mq-policy.yaml > $(params.output_file)
        sed -i -e "s|POLICY_NAME|$(params.policy_name)|g" $(params.output_file)
        sed -i -e "s|POLICY_VERSION|$(params.policy_version)|g" $(params.output_file)

        cat $(params.output_file)