apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: policy-pipeline
spec:
  workspaces:
    - name: workspace
  params:
    - name: git_url
      description: Git url
    - name: branch
      description: Revision to use
    - name: project_name
    - name: bar_file
    - name: project_path
    - name: policy_file
    - name: policy_name
    - name: policy_version
  tasks:
    - name: checkout
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.git_url)
        - name: revision
          value: $(params.branch)
        - name: deleteExisting
          value: 'true'
      workspaces:
        - name: output
          workspace: workspace
    - name: package
      taskRef:
        name: bar-package-task
        kind: Task
      runAfter:
        - checkout
      params:
        - name: project_path
          value: $(params.project_path)
        - name: project_name
          value: $(params.project_name)
        - name: bar_file
          value: $(params.bar_file)
      workspaces:
        - name: source
          workspace: workspace
    - name: configure
      taskRef:
        name: policy-configure-task
        kind: Task
      runAfter:
        - package
      params:
        - name: project_path
          value: $(params.project_path)
        - name: bar_file
          value: $(params.bar_file)
        - name : output_file 
          value: $(params.policy_file)
        - name: policy_name
          value: $(params.policy_name)
        - name: policy_version
          value: $(params.policy_version)
      workspaces:
        - name: source
          workspace: workspace
    - name: git-upload
      taskRef:
        name: git-upload
        kind: Task
      runAfter:
        - configure
      params:
        - name: revision
          value: $(params.branch)
        - name: project_path
          value: $(params.project_path)
        - name : target_file 
          value: $(params.policy_file)
      workspaces:
        - name: source
          workspace: workspace