apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: policy-configure-task
spec:
  workspaces:
    - name: source
  params:
    - name: bar_file
      type: string 
    - name: project_path
      type: string 
    - name: output_file
      type: string
  steps:
   - name: policy-package
     image: cp.icr.io/cp/appc/ace-server-prod:12.0.5.0-r3-20220830-142002@sha256:084cbd25b8af37c841f0b8d1ffc401e2805018baeb4ef6997a2ce9c1c97a1441
     workingDir: $(workspaces.source.path)/$(params.project_path)
     script: |
        #!/bin/sh
        
        export ENCODED_BAR=$(cat $(params.bar_file) | base64)
        echo $ENCODED_BAR

        sed 's|CONTENT_BAR|$ENCODED_BAR|g' templates/mq-policy.yaml > $(params.output_file)


        cat $(params.output_file)