kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: qm1-to-qm2-route
spec:
  host: qm12e-qm2.chl.mq.ibm.com
  to:
    kind: Service
    name: myqm-jt-02-ibm-mq
  port:
    targetPort: 1414
  tls:
    termination: passthrough
  wildcardPolicy: None