kind: ConfigMap
apiVersion: v1
metadata:
  name: mymq-jt-02
data:
  qm2.mqsc : |
    DEFINE QLOCAL('APPQ') REPLACE
    DEFINE QLOCAL('Q1') REPLACE 
    DEFINE QLOCAL('Q2') REPLACE
    DEFINE QLOCAL('Q1.REPLICA') REPLACE
    DEFINE QLOCAL('Q2.REPLICA') REPLACE

    DEFINE CHANNEL('APPCHL') CHLTYPE(SVRCONN) TRPTYPE(TCP) MCAUSER('app') REPLACE

    DEFINE CHANNEL('QM1.QM2') CHLTYPE (RCVR) TRPTYPE(TCP) SSLCIPH('ANY_TLS12_OR_HIGHER') SSLCAUTH(REQUIRED) MCAUSER('app') REPLACE

    SET CHLAUTH('*') TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(NOACCESS) DESCR('Back-stop rule - Blocks everyone') ACTION(REPLACE)
    SET CHLAUTH('APPCHL') TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(CHANNEL) CHCKCLNT(ASQMGR) DESCR('Allows connection via APP channel') ACTION(REPLACE)
    SET CHLAUTH('QM1.QM2') TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(CHANNEL) CHCKCLNT(ASQMGR) DESCR('Allows connection via APP channel') ACTION(REPLACE)

    SET AUTHREC PROFILE('APPQ') PRINCIPAL('app') OBJTYPE(QUEUE) AUTHADD(BROWSE,GET,INQ,PUT)
    SET AUTHREC PROFILE('Q1') PRINCIPAL('app') OBJTYPE(QUEUE) AUTHADD(BROWSE,GET,INQ,PUT)

    DEFINE AUTHINFO('DEV.AUTHINFO') AUTHTYPE(IDPWOS) CHCKCLNT(REQDADM) CHCKLOCL(OPTIONAL) ADOPTCTX(YES) REPLACE
    ALTER QMGR CONNAUTH('DEV.AUTHINFO')
    REFRESH SECURITY(*) TYPE(CONNAUTH)