apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: log-poc
  namespace: log-poc
spec:
  enableMetrics: true
  license:
    accept: true
    license: L-APEH-CCHL5W
    use: CloudPakForIntegrationNonProduction
  pod:
    containers:
      runtime:
        image: 'de.icr.io/clarins-hg-registry/logpoc:0.1'
        resources:
          limits:
            cpu: 300m
            memory: 368Mi
          requests:
            cpu: 300m
            memory: 368Mi
        volumeMounts:
          - mountPath: /home/aceuser/config
            name: log-config
    imagePullSecrets:
      - name: ibm-registry-access
    volumes:
      - configMap:
          items:
            - key: logger.xml
              path: logger.xml
          name: log-config
        name: log-config
  adminServerSecure: true
  router:
    timeout: 120s
  designerFlowsOperationMode: disabled
  createDashboardUsers: true
  service:
    endpointType: http
  version: 12.0.5.0-r1-lts
  replicas: 1
  configurations:
    - logpath
