kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
   prometheusK8s:
      remoteWrite:
      - url: <thanos_receiver_endpoint>
        headers:
          THANOS-TENANT: "npr"
      externalLabels:
        cluster: npr
        kind: infra
