apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: default-mymq-route
spec:
  host: appchl.chl.mq.ibm.com
  to:
    kind: Service
    name: myqm-ibm-mq
  port:
    targetPort: 1414
  tls:
    termination: passthrough
