apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  labels:
    app.kubernetes.io/instance: mydev
    eventstreams.ibm.com/cluster: mydev
  name: inbound
spec:
  config:
    min.insync.replicas: '2'
    retention.ms: '604800000'
  partitions: 3
  replicas: 3
  topicName: INBOUND