apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: qm1
spec:
  license:
    accept: true
    license: L-RJON-CD3JKX
    metric: VirtualProcessorCore
    use: NonProduction
  queueManager:
    name: QM1
    mqsc:
      - configMap:
          items:
            - qm1.mqsc
          name: myqm-configmap
    availability:
      type: SingleInstance
      updateStrategy: RollingUpdate
    storage:
      defaultClass: ibmc-block-gold
      queueManager:
        type: persistent-claim
  version: 9.2.5.0-r1
  web:
    enabled: true