apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: simpleaceapp
  namespace: cp4i
spec:
  enableMetrics: true
  license:
    accept: true
    license: L-APEH-C79J9U
    use: CloudPakForIntegrationNonProduction
  pod:
    containers:
      runtime:
        image: 'jtarte/simpleaceapp:latest'
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 300m
            memory: 350Mi
          requests:
            cpu: 300m
            memory: 300Mi
  adminServerSecure: true
  router:
    timeout: 120s
  designerFlowsOperationMode: disabled
  createDashboardUsers: true
  service:
    endpointType: http
  version: 12.0.3.0-r1
  replicas: 1