apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: acemq-sample
  labels:
    version: '1.2'
    generated-date: 'Thu_Oct_27_08_45_40_UTC_2022'
spec:
  enableMetrics: true
  license:
    accept: true
    license: L-APEH-CCHL5W
    use: CloudPakForIntegrationNonProduction
  pod:
    containers:
      runtime:
        image: docker.io/jtarte/mqsample:1.2
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 300m
            memory: 350Mi
          requests:
            cpu: 300m
            memory: 300Mi
  adminServerSecure: true
  router:
    timeout: 120s
  designerFlowsOperationMode: disabled
  createDashboardUsers: true
  service:
    endpointType: http
  version: 12.0.5.0-r3
  replicas: 1
  configurations:
    - mq-policy
